<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CardSortTile_sortOptionTil_1</name>
   <tag></tag>
   <elementGuidId>a41fb8a7-f6a5-475f-b0de-5c10713f7e6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[count(. | id(&quot;root&quot;)/div[@class=&quot;pageContainer___16wop&quot;]/div[@class=&quot;CardSelector_wrapper___3b9mv&quot;]/div[@class=&quot;CardSortList_wrapper___15Auk&quot;]/div[@class=&quot;CardSortList_inner___1ti8D&quot;]/div[@class=&quot;CardSortTile_sortOptionTile___3Lgxk&quot;]) = count(id(&quot;root&quot;)/div[@class=&quot;pageContainer___16wop&quot;]/div[@class=&quot;CardSelector_wrapper___3b9mv&quot;]/div[@class=&quot;CardSortList_wrapper___15Auk&quot;]/div[@class=&quot;CardSortList_inner___1ti8D&quot;]/div[@class=&quot;CardSortTile_sortOptionTile___3Lgxk&quot;])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CardSortTile_sortOptionTile___3Lgxk </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;pageContainer___16wop&quot;]/div[@class=&quot;CardSelector_wrapper___3b9mv&quot;]/div[@class=&quot;CardSortList_wrapper___15Auk&quot;]/div[@class=&quot;CardSortList_inner___1ti8D&quot;]/div[@class=&quot;CardSortTile_sortOptionTile___3Lgxk&quot;]</value>
   </webElementProperties>
</WebElementEntity>
